name: Build Woof! (Windows ARM64/AArch64)

on:
  push:
    branches:
      - master

jobs:
  build-winarm64:
    runs-on: windows-11-arm
    steps:
      - name: 'Configure git: core.autocrlf, core.eol'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          pacboy: >-
            cmake:p
            fluidsynth:p
            libebur128:p
            libsndfile:p
            libxmp:p
            ninja:p
            openal:p
            SDL2:p
            toolchain:p
      - name: Build
        shell: msys2 {0}
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DENABLE_WERROR=ON -DENABLE_HARDENING=ON -DENABLE_LTO=ON
          cmake --build build
      - name: Copy files
        shell: msys2 {0}
        run: |
          cd build
          mkdir upload
          cpack -G TAR -B cpack_extract
          cd cpack_extract
          rm -rf _CPack_Packages/
          tar -xf *.tar
          cp -r $(ls -d */|head -n 1)/* ../upload
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Woof-git-winarm64-${{github.sha}}
          path: build/upload
          if-no-files-found: error
